[build]
  command = "cd frontend && npm install && npm run build"  # Install dependencies before building
  publish = "frontend/dist"  # Make sure this is the correct build output folder (usually 'dist' for Vite)
  
  ## Uncomment to use this redirect for Single Page Applications (SPA) like React or Vite
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Settings for Netlify Dev (if you want to run locally)
#[dev]
#  command = "npm run dev"  # Command to start your dev server (for local development)
#  port = 3000             # Port that the dev server will be listening on
#  publish = "frontend/dist"  # Folder with static content (for SPA handling)
