name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-26"
compatibility_flags = [ "nodejs_compat" ]


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiM2ZmMjFmZWUtMDI3Yi00NTVlLWI2NTctNDRmZDYwNjc3M2FiIiwidGVuYW50X2lkIjoiMzU0ZmY0ZTA2M2I5MTc3YThiNzEyOTQ4MWNjNGM3Yjk3MTZhNDJjOTM5MGE0MDdkOTE5MDkwOWI0ZjcwNjU4MyIsImludGVybmFsX3NlY3JldCI6IjZiNDY2YjIwLTQ3NWQtNGY4MS1hZGUxLWU0ZWEyY2E0NjFjYiJ9.dG27CNFojOlV3g5wyGPOZyWPvuuAHS5a9XADJK0R2wo"
JWT_SECRET = "patpattison"
BACKEND_URL = "https://backend.sensebound4.workers.dev"
